#!/usr/bin/env bash
# bsdinstall.sh — Drive bsdinstall(8) in scripted mode + own the re-entrancy that
# bsdinstall itself does not provide (wipe / export / re-mount).
#
# A bsdinstall script file = PREAMBLE (sh variable assignments read at start) then
# a SETUP SCRIPT after the `#!/bin/sh` line that runs chrooted in the new system
# at ${MOUNTPOINT}. We keep the setup script MINIMAL (base sysrc, users, locale,
# pkg bootstrap, shell layer); the long failure-prone pkg phases (gpu/desktop)
# run later as our own checkpointed chroot phases so --resume can skip them.
source "${LIB_DIR}/protection.sh"

# _mib_to_size — MiB integer -> a gpart-friendly size token (Ng if whole GiB else Nm)
_mib_to_size() {
    local mib="$1"
    if (( mib % 1024 == 0 )); then
        echo "$(( mib / 1024 ))g"
    else
        echo "${mib}m"
    fi
}

# _resolve_part_by_type — echo provider (e.g. nda0p2) of the first partition of
# the given gpart type on TARGET_DISK. Used to re-find root/ESP after install.
_resolve_part_by_type() {
    local want="$1"
    gpart show -p "${TARGET_DISK}" 2>/dev/null \
        | awk -v t="${want}" 'NF>=4 && $4==t {print $3; exit}' || true
}

# --- script generation --------------------------------------------------------

# bsdinstall_generate_script — render ${BSDINSTALL_SCRIPT} from CONFIG_VARS.
bsdinstall_generate_script() {
    einfo "Generating bsdinstall script (${FS_PROFILE} profile) -> ${BSDINSTALL_SCRIPT}"

    local swap_token="0"
    if [[ "${SWAP_TYPE:-none}" == "partition" && "${SWAP_SIZE_MIB:-0}" -gt 0 ]]; then
        swap_token="$(_mib_to_size "${SWAP_SIZE_MIB}")"
    fi

    # Create the file 0600 from inception (umask 077): it carries the root/user
    # $6$ hashes, so it must never exist world-readable even momentarily.
    ( umask 077
    {
        printf '# Generated by %s v%s — DO NOT EDIT (regenerated each run)\n' \
            "${INSTALLER_NAME}" "${INSTALLER_VERSION}"
        printf 'DISTRIBUTIONS="%s"\n' "${DIST_DEFAULT}"
        # Point distextract at the offline dist set, and pin a default mirror so a
        # NEEDED fetch (mini-memstick: no base.txz in ${DIST_DIR}) stays
        # non-interactive instead of dropping into bsdinstall's mirrorselect
        # dialog despite nonInteractive=YES. BSDINSTALL_DISTSITE is consulted ONLY
        # when a dist file is missing locally, so a full memstick still extracts
        # offline (no network touched).
        printf 'export BSDINSTALL_DISTDIR="%s"\n' "${DIST_DIR}"
        if [[ -n "${DIST_SITE:-}" ]]; then
            printf 'export BSDINSTALL_DISTSITE="%s"\n' "${DIST_SITE}"
        else
            printf 'export BSDINSTALL_DISTSITE="https://download.freebsd.org/releases/amd64/amd64/%s/"\n' \
                "$(uname -r 2>/dev/null | sed 's/-p[0-9]*$//')"
        fi
        printf 'export nonInteractive=YES\n'

        if [[ "${FS_PROFILE}" == "zfs" ]]; then
            _emit_zfs_preamble "${swap_token}"
        else
            _emit_ufs_preamble "${swap_token}"
        fi

        # root password hash (pw -H 0; ROOTPASS_ENC wins over ROOTPASS_PLAIN)
        [[ -n "${ROOT_PASSWORD_HASH:-}" ]] && printf 'export ROOTPASS_ENC=%q\n' "${ROOT_PASSWORD_HASH}"

        printf '\n#!/bin/sh\n'
        _emit_setup_script
    } > "${BSDINSTALL_SCRIPT}"
    )

    # Belt-and-suspenders: the umask above already created it 0600.
    chmod 600 "${BSDINSTALL_SCRIPT}" 2>/dev/null || true
}

# _emit_zfs_preamble — root-on-ZFS auto layout (whole-disk, single vdev).
_emit_zfs_preamble() {
    local swap_token="$1"
    printf 'export ZFSBOOT_DISKS="%s"\n' "${TARGET_DISK}"
    printf 'export ZFSBOOT_VDEV_TYPE="%s"\n' "${ZFS_VDEV_TYPE:-${ZFS_VDEV_TYPE_DEFAULT}}"
    printf 'export ZFSBOOT_POOL_NAME="%s"\n' "${ZFS_POOL_NAME:-${ZFS_POOL_NAME_DEFAULT}}"
    printf 'export ZFSBOOT_CONFIRM_LAYOUT=0\n'
    printf 'export ZFSBOOT_FORCE_4K_SECTORS=1\n'
    printf 'export ZFSBOOT_POOL_CREATE_OPTIONS=%q\n' "${ZFS_POOL_OPTS:-${ZFS_POOL_OPTS_DEFAULT}}"
    # BOOT_TYPE: leave to auto-detect (machdep.bootmethod) unless forced.
    case "${BOOT_TYPE:-auto}" in
        UEFI|BIOS|BIOS+UEFI) printf 'export ZFSBOOT_BOOT_TYPE="%s"\n' "${BOOT_TYPE}" ;;
    esac
    printf 'export ZFSBOOT_SWAP_SIZE="%s"\n' "${swap_token}"
    [[ "${SWAP_ENCRYPTION:-0}" == "1" ]] && printf 'export ZFSBOOT_SWAP_ENCRYPTION=1\n'
    # GELI full-disk root is OPT-IN and NOT fully scripted: even under
    # nonInteractive=YES, zfsboot's geli flow PROMPTS on the console for the disk
    # encryption passphrase (there is no passphrase knob in this preamble). The
    # install therefore pauses for interactive passphrase entry at this point —
    # that is expected, not a hang. The filesystem_select screen already warns to
    # verify boot-unlock on this exact hardware before relying on it.
    if [[ "${GELI_ROOT:-0}" == "1" ]]; then
        printf 'export ZFSBOOT_GELI_ENCRYPTION=1\n'
        printf 'export ZFSBOOT_GELI_KEY_FILE="/boot/encryption.key"\n'
    fi
}

# _emit_ufs_preamble — GPT + boot + swap + single UFS root via PARTITIONS.
# The PARTITIONS list is taken verbatim — bsdinstall does NOT auto-add a boot
# partition — so the boot partition MUST match the firmware: UEFI -> an `efi`
# ESP, BIOS -> a `freebsd-boot` partition (for the gptboot bootcode), BIOS+UEFI
# -> both. An efi-only layout is UNBOOTABLE on a pure-BIOS machine. 'auto' cannot
# be resolved at generation time (no machdep.bootmethod here), so it falls back
# to UEFI (the installer's first-class target); a BIOS box must set BOOT_TYPE=BIOS.
_emit_ufs_preamble() {
    local swap_token="$1"
    local boot_part
    case "${BOOT_TYPE:-auto}" in
        BIOS)        boot_part="512k freebsd-boot" ;;
        BIOS+UEFI)   boot_part="512k freebsd-boot, ${ESP_SIZE_MIB}M efi" ;;
        UEFI|auto|*) boot_part="${ESP_SIZE_MIB}M efi" ;;
    esac
    local parts="${boot_part}"
    [[ "${swap_token}" != "0" ]] && parts+=", ${swap_token} freebsd-swap"
    parts+=", auto freebsd-ufs /"
    printf 'PARTITIONS="%s GPT { %s }"\n' "${TARGET_DISK}" "${parts}"
}

# _emit_setup_script — minimal chrooted post-install. Heredoc body is expanded
# HERE (host) so CONFIG_VARS interpolate into the generated file.
_emit_setup_script() {
    local groups="${USER_GROUPS:-wheel,operator,video}"
    # %q-quote every user-controlled value that becomes a /bin/sh TOKEN in the
    # generated setup script, so a FULLNAME / TIMEZONE / KEYMAP / group list
    # containing a space, quote, $, backtick or $(...) cannot break or inject into
    # the script bsdinstall(8) runs chrooted in /mnt. The %q output carries its
    # own quoting, so it is substituted BARE (no surrounding quotes). LOCALE /
    # LOCALE_CLASS are deliberately NOT %q'd: they are validated (xx_XX.UTF-8 /
    # the fixed 'english' class) and land in login.conf TEXT, where shell quoting
    # would corrupt the capability record.
    local q_host q_user q_full q_tz q_groups
    printf -v q_host   '%q' "${HOSTNAME:-}"
    printf -v q_user   '%q' "${USERNAME:-}"
    printf -v q_full   '%q' "${FULLNAME:-${USERNAME:-}}"
    printf -v q_tz     '%q' "${TIMEZONE:-}"
    printf -v q_groups '%q' "${groups}"
    local keymap_line=""
    if [[ -n "${KEYMAP:-}" ]]; then
        local q_keymap; printf -v q_keymap '%q' "${KEYMAP}"
        keymap_line="sysrc keymap=${q_keymap}"
    fi
    cat <<SETUP
set -e
[ -s /etc/resolv.conf ] || echo 'nameserver 1.1.1.1' > /etc/resolv.conf

# hostname + hosts
sysrc hostname=${q_host}
printf '127.0.0.1\t%s %s.local\n::1\t\t%s %s.local\n' ${q_host} ${q_host} ${q_host} ${q_host} >> /etc/hosts

# base services
$( [[ "${FS_PROFILE}" == "zfs" ]] && echo 'sysrc zfs_enable=YES' )
sysrc ifconfig_DEFAULT=DHCP
sysrc sshd_enable=YES
sysrc sendmail_enable=NONE
sysrc ntpd_enable=YES
sysrc ntpd_sync_on_start=YES
sysrc moused_enable=YES

# timezone / console keymap
tzsetup ${q_tz} || cp -f /usr/share/zoneinfo/${q_tz} /etc/localtime || true
${keymap_line}

# locale via login.conf class (FreeBSD has no /etc/locale.conf)
if ! grep -q '^${LOCALE_CLASS:-english}|' /etc/login.conf 2>/dev/null; then
cat >> /etc/login.conf <<'LOGINCONF'

${LOCALE_CLASS:-english}|UTF-8 login class:\\
	:charset=UTF-8:\\
	:lang=${LOCALE:-en_US.UTF-8}:\\
	:tc=default:
LOGINCONF
fi
cap_mkdb /etc/login.conf

# user account (hash via stdin, never argv)
if [ -n ${q_user} ] && ! pw usershow ${q_user} >/dev/null 2>&1; then
    pw useradd -n ${q_user} -c ${q_full} -d /home/${q_user} -m -s /usr/local/bin/bash -G ${q_groups} -L "${LOCALE_CLASS:-english}"
fi
$( [[ -n "${USER_PASSWORD_HASH:-}" ]] && printf 'printf %%s %q | pw usermod -n %q -H 0\n' "${USER_PASSWORD_HASH}" "${USERNAME}" )

# pkg + shell layer for the installed system
ASSUME_ALWAYS_YES=yes pkg bootstrap -f || true
pkg update -f || true
pkg install -y bash git ${PRIV_TOOL:-doas} || true
$( [[ "${PRIV_TOOL:-doas}" == "doas" ]] && printf 'echo "permit persist :wheel" > /usr/local/etc/doas.conf\n' )

# loader.conf (boot-critical only)
$( [[ "${FS_PROFILE}" == "zfs" ]] && echo 'sysrc -f /boot/loader.conf zfs_load=YES' )
$( [[ -n "${ARC_MAX_BYTES:-}" ]] && echo "sysrc -f /boot/loader.conf vfs.zfs.arc_max=${ARC_MAX_BYTES}" )
SETUP
}

# --- destructive run + re-entrancy --------------------------------------------

# bsdinstall_wipe_target — make the target safe to (re)install: export any pool,
# disable its swap, unmount ${MOUNTPOINT}, clear stale GPT/ZFS labels. bsdinstall
# auto-ZFS also gpart-destroys, but a half-finished previous run can leave an
# imported pool / labels that make it fail — so we clean first. Idempotent.
bsdinstall_wipe_target() {
    if [[ "${DRY_RUN:-0}" == "1" ]]; then
        einfo "[DRY-RUN] would wipe ${TARGET_DISK} (export pool, gpart destroy, labelclear)"
        return 0
    fi
    einfo "Preparing ${TARGET_DISK} for install (wipe)..."
    swapoff -a 2>/dev/null || true
    local pool="${ZFS_POOL_NAME:-${ZFS_POOL_NAME_DEFAULT}}"
    zpool export -f "${pool}" 2>/dev/null || true
    umount -f "${MOUNTPOINT}/dev" 2>/dev/null || true
    umount -f "${MOUNTPOINT}/boot/efi" 2>/dev/null || true
    umount -f "${MOUNTPOINT}" 2>/dev/null || true
    local p
    for p in $(gpart show -p "${TARGET_DISK}" 2>/dev/null | awk 'NF>=4 && $3 ~ /[ps][0-9]+$/{print $3}'); do
        zpool labelclear -f "/dev/${p}" 2>/dev/null || true
    done
    gpart destroy -F "${TARGET_DISK}" 2>/dev/null || true
}

# bsdinstall_run — wipe + execute the scripted install.
bsdinstall_run() {
    bsdinstall_generate_script
    bsdinstall_wipe_target
    if [[ "${DRY_RUN:-0}" == "1" ]]; then
        einfo "[DRY-RUN] would run: bsdinstall script ${BSDINSTALL_SCRIPT}"
        einfo "[DRY-RUN] generated script:"
        cat "${BSDINSTALL_SCRIPT}" >&2 || true
        return 0
    fi
    try "Running bsdinstall (base system + bootloader + users)" \
        bsdinstall script "${BSDINSTALL_SCRIPT}"
}

# bsdinstall_mount_target — re-import/re-mount the freshly installed system at
# ${MOUNTPOINT} so our post-install chroot phases can run. bsdinstall unmounts on
# completion, so we bring it back up. Idempotent.
bsdinstall_mount_target() {
    if [[ "${DRY_RUN:-0}" == "1" ]]; then
        einfo "[DRY-RUN] would mount target at ${MOUNTPOINT}"
        return 0
    fi
    mkdir -p "${MOUNTPOINT}"
    if [[ "${FS_PROFILE}" == "zfs" ]]; then
        local pool="${ZFS_POOL_NAME:-${ZFS_POOL_NAME_DEFAULT}}"
        if ! zpool list "${pool}" >/dev/null 2>&1; then
            # -N: import WITHOUT auto-mounting so we can mount the root boot
            # environment FIRST; otherwise the child datasets (canmount=on) mount
            # onto an empty ${MOUNTPOINT} and shadow the root once it appears.
            try "Importing ZFS pool ${pool}" zpool import -f -N -R "${MOUNTPOINT}" "${pool}"
        fi
        # The root filesystem lives in the ACTIVE boot environment (e.g.
        # ${pool}/ROOT/default), which has canmount=noauto — neither `zpool
        # import` nor `zfs mount -a` mounts it. Mount the bootfs explicitly, or
        # ${MOUNTPOINT} stays empty and every post-install chroot phase dies with
        # "chroot: env: No such file or directory".
        local be
        be="$(zpool get -H -o value bootfs "${pool}" 2>/dev/null || true)"
        if [[ -n "${be}" && "${be}" != "-" ]] && ! mount | grep -q " on ${MOUNTPOINT} (zfs"; then
            try "Mounting boot environment ${be}" zfs mount "${be}"
        fi
        zfs mount -a 2>/dev/null || true
        # Also mount the ESP: the finalize phase re-pins the EFI boot entry and
        # resolves the loader path, and FreeBSD efibootmgr -l needs the ESP
        # mounted. The ZFS-auto layout puts the `efi` partition on TARGET_DISK.
        # Best-effort — chroot_teardown unmounts /boot/efi for both profiles.
        local zfs_esp_part
        zfs_esp_part="$(_resolve_part_by_type efi)"
        if [[ -n "${zfs_esp_part}" ]]; then
            mkdir -p "${MOUNTPOINT}/boot/efi"
            mount -t msdosfs "/dev/${zfs_esp_part}" "${MOUNTPOINT}/boot/efi" 2>/dev/null || true
        fi
    else
        local root_part esp_part
        root_part="$(_resolve_part_by_type freebsd-ufs)"
        [[ -n "${root_part}" ]] && try "Mounting UFS root /dev/${root_part}" mount "/dev/${root_part}" "${MOUNTPOINT}"
        esp_part="$(_resolve_part_by_type efi)"
        if [[ -n "${esp_part}" ]]; then
            mkdir -p "${MOUNTPOINT}/boot/efi"
            mount -t msdosfs "/dev/${esp_part}" "${MOUNTPOINT}/boot/efi" 2>/dev/null || true
        fi
    fi
    # devfs + DNS for chrooted pkg
    mount -t devfs devfs "${MOUNTPOINT}/dev" 2>/dev/null || true
    cp -f /etc/resolv.conf "${MOUNTPOINT}/etc/resolv.conf" 2>/dev/null || true
}
